apiVersion: v1
kind: Namespace
metadata:
  name: edge-client-agent
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: edge-client-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
  namespace: edge-client-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: edge-client-agent
---
apiVersion: v1
data:
  .env: |
    ENV=LOCAL
    APP_DEBUG=TRUE
    PORT=9000
    SSL=FALSE
    DB=TRUE
    DB_USER="postgres"
    DB_PASS="postgres"
    DB_HOST="postgres-external.default.svc"
    DB_PORT="5432"
    DB_NAME="postgresdb"
    DB_OPTIONS="sslmode=disable TimeZone=Asia/Taipei"
    ACCESS_SECRET="ashasdjhjhjadhasdaa123"
    REFERSH_SECRET="hjsajdhkjhf41jhagggdga"
    REDIS_SECRET="hjfhjhasdfkyuy2"
    REDIS_HOST=127.0.0.1:6379
    REDIS_PASSWORD=
    KUBE_CONFIG=
kind: ConfigMap
metadata:
  namespace: edge-client-agent
  name: edge-agent-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: edge-agent
  name: edge-agent
  namespace: edge-client-agent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: edge-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: edge-agent
    spec:
      containers:
      - image: itrixedge/edge-client-agent:1104874-arm64
        imagePullPolicy: IfNotPresent
        name: edge-agent
        volumeMounts:
        - name: edge-agent-config-volume
          mountPath: /config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: edge-agent-config-volume
          configMap:
            name: edge-agent-config
      dnsPolicy: ClusterFirst
      serviceAccountName: admin-user
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: edge-client-agent
  labels:
    run: edge-agent
  name: edge-agent
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: edge-agent
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
